{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--                                               // emit // config
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--
--   "Machine dreams hold a special vertigo. Turner lay down on a virgin
--    slab of green temperfoam in the makeshift dorm and jacked
--    Mitchell's dossier."
--
--                                                                 — Count Zero
--
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--                                                     // emit // generation
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

module NixCompile.Emit.Config (
    -- * Generation
    emitConfigFunction,
    emitConfigJson,
    emitConfigYaml,
    emitConfigToml,

    -- * Schema helpers
    ConfigTree (..),
    buildConfigTree,
)
where

import Data.List (sortOn)
import Data.Map.Strict (Map)
import Data.Map.Strict qualified as Map
import Data.Text (Text)
import Data.Text qualified as T
import Numeric (showHex)

import NixCompile.Types

jsonEscape :: Text -> Text
jsonEscape = T.concatMap $ \character -> case character of
    '"' -> "\\\""
    '\\' -> "\\\\"
    '\n' -> "\\n"
    '\r' -> "\\r"
    '\t' -> "\\t"
    '\b' -> "\\b"
    '\f' -> "\\f"
    _
        | character < '\x20' -> "\\u" <> T.justifyRight 4 '0' (T.pack (showHex (fromEnum character) ""))
        | otherwise -> T.singleton character

renderJsonLit :: Literal -> Text
renderJsonLit = \case
    LitInt n -> T.pack (show n)
    LitBool True -> "true"
    LitBool False -> "false"
    LitString s -> "\"" <> jsonEscape s <> "\""
    LitPath sp -> "\"" <> jsonEscape (unStorePath sp) <> "\""

renderYamlLit :: Literal -> Text
renderYamlLit = \case
    LitInt n -> T.pack (show n)
    LitBool True -> "true"
    LitBool False -> "false"
    LitString s -> "\"" <> jsonEscape s <> "\""
    LitPath sp -> "\"" <> jsonEscape (unStorePath sp) <> "\""

renderTomlLit :: Literal -> Text
renderTomlLit = \case
    LitInt n -> T.pack (show n)
    LitBool True -> "true"
    LitBool False -> "false"
    LitString s -> "\"" <> jsonEscape s <> "\""
    LitPath sp -> "\"" <> jsonEscape (unStorePath sp) <> "\""

data ConfigTree
    = ConfigBranch !(Map Text ConfigTree)
    | ConfigLeaf !ConfigSpec
    deriving (Eq, Show)

buildConfigTree :: Map ConfigPath ConfigSpec -> ConfigTree
buildConfigTree specs = foldr insertPath (ConfigBranch Map.empty) (Map.toList specs)
  where
    insertPath ([], spec) _ = ConfigLeaf spec
    insertPath (key : keys, spec) (ConfigBranch m) =
        ConfigBranch $ Map.alter (Just . go keys spec) key m
    insertPath _ leaf = leaf
    go [] spec Nothing = ConfigLeaf spec
    go [] spec (Just _) = ConfigLeaf spec
    go (key : keys) spec Nothing =
        ConfigBranch $ Map.singleton key (go keys spec Nothing)
    go (key : keys) spec (Just (ConfigBranch m)) =
        ConfigBranch $ Map.alter (Just . go keys spec) key m
    go _ _spec (Just leaf) = leaf

-- ── emit-config bash function ─────────────────────────────────────

emitConfigFunction :: Schema -> Text
emitConfigFunction schema =
    T.unlines $
        concat
            [ emitConfigHeader
            , emitEscapeJsonFn
            , emitRequireIntFn
            , emitRequireBoolFn
            , emitRuntimeBlock schema
            ]

emitConfigHeader :: [Text]
emitConfigHeader =
    [ "# Generated by nix-compile - do not edit"
    , "emit-config() {"
    ]

emitEscapeJsonFn :: [Text]
-- shell-native JSON string escaper; mirrors the Haskell jsonEscape logic
emitEscapeJsonFn =
    [ "  __nix_compile_escape_json() {"
    , "    local s=\"$1\" out=\"\" c code esc i"
    , "    for ((i = 0; i < ${#s}; i++)); do"
    , "      c=\"${s:i:1}\""
    , "      case \"$c\" in"
    , "        '\"') out+='\\\"' ;;"
    , "        '\\') out+='\\\\' ;;"
    , "        $'\\n') out+='\\n' ;;"
    , "        $'\\r') out+='\\r' ;;"
    , "        $'\\t') out+='\\t' ;;"
    , "        $'\\b') out+='\\b' ;;"
    , "        $'\\f') out+='\\f' ;;"
    , "        *)"
    , "          printf -v code '%d' \"'$c\""
    , "          if (( code < 32 )); then"
    , "            printf -v esc '\\\\u%04x' \"$code\""
    , "            out+=\"$esc\""
    , "          else"
    , "            out+=\"$c\""
    , "          fi"
    , "          ;;"
    , "      esac"
    , "    done"
    , "    printf '%s' \"$out\""
    , "  }"
    ]

emitRequireIntFn :: [Text]
-- n.b. checks both value-shape and JSON lexical rules (no leading zeros)
emitRequireIntFn =
    [ "  __nix_compile_require_int() {"
    , "    case \"$2\" in"
    , "      -[0-9]*|[0-9]*) ;;"
    , "      *) echo \"$1 must be an integer\" >&2; return 1 ;;"
    , "    esac"
    , "    case \"$2\" in"
    , "      *[!0-9-]*|*-*-*|*-) "
    , "        echo \"$1 must be an integer\" >&2; return 1 ;;"
    , "    esac"
    , "    case \"$2\" in"
    , "      0|-0|[1-9]*|-[1-9]*) ;;"
    , "      *) echo \"$1 must be a JSON integer (no leading zeros)\" >&2; return 1 ;;"
    , "    esac"
    , "    case \"$2\" in"
    , "      *) printf '%s' \"$2\" ;;"
    , "    esac"
    , "  }"
    ]

emitRequireBoolFn :: [Text]
emitRequireBoolFn =
    [ "  __nix_compile_require_bool() {"
    , "    case \"$2\" in"
    , "      true|false) printf '%s' \"$2\" ;;"
    , "      *) echo \"$1 must be true or false\" >&2; return 1 ;;"
    , "    esac"
    , "  }"
    ]

emitRuntimeBlock :: Schema -> [Text]
-- format dispatch + runtime guards; renderRuntimeGuards is multi-line
emitRuntimeBlock schema =
    [ "  local format=\"${1:-json}\""
    , renderRuntimeGuards schema
    , "  case \"$format\" in"
    , "    json)"
    , "      " <> emitConfigJson schema
    , "      ;;"
    , "    yaml)"
    , "      " <> emitConfigYaml schema
    , "      ;;"
    , "    toml)"
    , "      " <> emitConfigToml schema
    , "      ;;"
    , "    *)"
    , "      echo \"Unknown format: $format\" >&2"
    , "      return 1"
    , "      ;;"
    , "  esac"
    , "}"
    ]

isRequiredEnv :: Map Text EnvSpec -> Text -> Bool
isRequiredEnv env var = case Map.lookup var env of
    Just envSpec -> envRequired envSpec
    Nothing -> True

renderRuntimeGuards :: Schema -> Text
renderRuntimeGuards schema =
    T.unlines
        [ guardLine
        | spec <- Map.elems (schemaConfig schema)
        , guardLine <- renderGuards spec
        ]
  where
    env = schemaEnv schema

    renderGuards ConfigSpec{cfgFrom = Just var, cfgType = ty, cfgQuoted = quoted}
        | isRequiredEnv env var =
            if quoted == Just Quoted
                then [presenceGuard var]
                else case ty of
                    TInt -> [intGuard var]
                    TNumeric -> [intGuard var]
                    TBool -> [boolGuard var]
                    _ -> [presenceGuard var]
        | otherwise = []
    renderGuards ConfigSpec{cfgTemplate = Just parts} =
        [presenceGuard var | var <- requiredTemplateVars parts, isRequiredEnv env var]
    renderGuards _ = []

    presenceGuard var = "  : \"${" <> var <> ":?" <> var <> " is required}\""
    intGuard var = "  __nix_compile_require_int \"" <> var <> "\" \"${" <> var <> ":?" <> var <> " is required}\" >/dev/null || return 1"
    boolGuard var = "  __nix_compile_require_bool \"" <> var <> "\" \"${" <> var <> ":?" <> var <> " is required}\" >/dev/null || return 1"

    requiredTemplateVars = concatMap $ \case
        ConfigVar var -> [var]
        ConfigVarRequired var -> [var]
        _ -> []

emitConfigJson :: Schema -> Text
emitConfigJson schema =
    let env = schemaEnv schema
        tree = buildConfigTree (schemaConfig schema)
     in emitTemplate (renderJsonTree env 0 tree)

escapeForPrintf :: Text -> Text
escapeForPrintf = T.concatMap $ \case
    '\'' -> "'\\''"
    character -> T.singleton character

data Template = Template !Text ![Text]

appendTemplate :: Template -> Template -> Template
appendTemplate (Template a as) (Template b bs) = Template (a <> b) (as ++ bs)

concatTemplates :: [Template] -> Template
concatTemplates = foldr appendTemplate (Template "" [])

literalTemplate :: Text -> Template
literalTemplate text = Template (T.replace "%" "%%" text) []

dynamicTemplate :: Text -> Template
dynamicTemplate arg = Template "%s" [arg]

emitTemplate :: Template -> Text
emitTemplate (Template fmt args) =
    "printf '" <> escapeForPrintf (fmt <> "\n") <> "'" <> argsText
  where
    argsText
        | null args = ""
        | otherwise = " " <> T.unwords (map quoteShellArg args)

    quoteShellArg arg = "\"" <> arg <> "\""

intersperseTemplate :: Template -> [Template] -> [Template]
intersperseTemplate _ [] = []
intersperseTemplate _ [x] = [x]
intersperseTemplate sep (x : xs) = x : sep : intersperseTemplate sep xs

renderJsonTree :: Map Text EnvSpec -> Int -> ConfigTree -> Template
renderJsonTree env indent = \case
    ConfigBranch m | Map.null m -> literalTemplate "{}"
    ConfigBranch m ->
        let entries = Map.toList m
            rendered = map (renderEntry indent) entries
            indentStr = T.replicate indent "  "
            nextIndent = T.replicate (indent + 1) "  "
         in concatTemplates $
                [literalTemplate "{\n"]
                    ++ intersperseTemplate (literalTemplate ",\n") (map (appendTemplate (literalTemplate nextIndent)) rendered)
                    ++ [literalTemplate ("\n" <> indentStr <> "}")]
    ConfigLeaf spec -> renderJsonValue env spec
  where
    renderEntry ind (key, subtree) =
        literalTemplate ("\"" <> key <> "\": ") `appendTemplate` renderJsonTree env (ind + 1) subtree

renderJsonValue :: Map Text EnvSpec -> ConfigSpec -> Template
renderJsonValue env ConfigSpec{..} =
    case (cfgFrom, cfgLit, cfgTemplate) of
        (_, Just lit, _) ->
            literalTemplate (renderJsonLit lit)
        (_, _, Just parts) ->
            literalTemplate "\"" `appendTemplate` renderTemplateParts parts `appendTemplate` literalTemplate "\""
        (Just var, _, _) ->
            let required = isRequiredEnv env var
                forceString = cfgQuoted == Just Quoted
                asString =
                    forceString || case cfgType of
                        TString -> True
                        TPath -> True
                        TVar _ -> True
                        _ -> False
                guardedVar
                    | required = "${" <> var <> ":?" <> var <> " is required}"
                    | otherwise = "${" <> var <> ":-}"
             in if asString
                    then literalTemplate "\"" `appendTemplate` dynamicTemplate ("$(__nix_compile_escape_json \"" <> guardedVar <> "\")") `appendTemplate` literalTemplate "\""
                    else dynamicTemplate guardedVar
        _ ->
            literalTemplate "null"

emitConfigYaml :: Schema -> Text
emitConfigYaml schema =
    let env = schemaEnv schema
        tree = buildConfigTree (schemaConfig schema)
     in emitTemplate (renderYamlTree env 0 tree)

renderYamlTree :: Map Text EnvSpec -> Int -> ConfigTree -> Template
renderYamlTree env indent = \case
    ConfigBranch m | Map.null m -> literalTemplate "{}"
    ConfigBranch m ->
        let entries = sortOn fst (Map.toList m)
            rendered = map (renderYamlEntry indent) entries
         in concatTemplates (intersperseTemplate (literalTemplate "\n") rendered)
    ConfigLeaf spec -> renderYamlValue env spec
  where
    renderYamlEntry ind (key, subtree) =
        let indentStr = T.replicate ind "  "
         in case subtree of
                ConfigBranch _ ->
                    literalTemplate (indentStr <> key <> ":\n") `appendTemplate` renderYamlTree env (ind + 1) subtree
                ConfigLeaf spec' ->
                    literalTemplate (indentStr <> key <> ": ") `appendTemplate` renderYamlValue env spec'

renderYamlValue :: Map Text EnvSpec -> ConfigSpec -> Template
renderYamlValue env ConfigSpec{..} =
    case (cfgFrom, cfgLit, cfgTemplate) of
        (_, Just lit, _) ->
            literalTemplate (renderYamlLit lit)
        (_, _, Just parts) ->
            literalTemplate "\"" `appendTemplate` renderTemplateParts parts `appendTemplate` literalTemplate "\""
        (Just var, _, _) ->
            let required = isRequiredEnv env var
                forceString = cfgQuoted == Just Quoted
                asString =
                    forceString || case cfgType of
                        TString -> True
                        TPath -> True
                        TVar _ -> True
                        _ -> False
                guardedVar
                    | required = "${" <> var <> ":?" <> var <> " is required}"
                    | otherwise = "${" <> var <> ":-}"
             in if asString
                    then literalTemplate "\"" `appendTemplate` dynamicTemplate ("$(__nix_compile_escape_json \"" <> guardedVar <> "\")") `appendTemplate` literalTemplate "\""
                    else dynamicTemplate guardedVar
        _ ->
            literalTemplate "null"

emitConfigToml :: Schema -> Text
emitConfigToml schema =
    let env = schemaEnv schema
        tree = buildConfigTree (schemaConfig schema)
     in emitTemplate (renderTomlTree env [] tree)

renderTomlTree :: Map Text EnvSpec -> [Text] -> ConfigTree -> Template
renderTomlTree env path = \case
    ConfigBranch m | Map.null m -> literalTemplate ""
    ConfigBranch m ->
        let (leaves, branches) = Map.partitionWithKey isLeaf m
            isLeaf _ (ConfigLeaf _) = True
            isLeaf _ _ = False
            sectionHeader =
                if not (null path) && not (Map.null leaves)
                    then "[" <> T.intercalate "." path <> "]\n"
                    else ""
            leafLines = map renderTomlLeaf (sortOn fst (Map.toList leaves))
            branchLines = map (renderTomlBranch path) (sortOn fst (Map.toList branches))
         in concatTemplates $
                [literalTemplate sectionHeader]
                    ++ intersperseTemplate (literalTemplate "\n") leafLines
                    ++ [literalTemplate (if not (Map.null leaves) && not (Map.null branches) then "\n\n" else "")]
                    ++ intersperseTemplate (literalTemplate "\n\n") branchLines
    ConfigLeaf _ -> literalTemplate ""
  where
    renderTomlLeaf (key, ConfigLeaf spec) =
        literalTemplate (key <> " = ") `appendTemplate` renderTomlValue env spec
    renderTomlLeaf _ = literalTemplate ""

    renderTomlBranch parentPath (key, subtree) =
        renderTomlTree env (parentPath ++ [key]) subtree

renderTomlValue :: Map Text EnvSpec -> ConfigSpec -> Template
renderTomlValue env ConfigSpec{..} =
    case (cfgFrom, cfgLit, cfgTemplate) of
        (_, Just lit, _) ->
            literalTemplate (renderTomlLit lit)
        (_, _, Just parts) ->
            literalTemplate "\"" `appendTemplate` renderTemplateParts parts `appendTemplate` literalTemplate "\""
        (Just var, _, _) ->
            let required = isRequiredEnv env var
                forceString = cfgQuoted == Just Quoted
                asString =
                    forceString || case cfgType of
                        TString -> True
                        TPath -> True
                        TVar _ -> True
                        _ -> False
                guardedVar
                    | required = "${" <> var <> ":?" <> var <> " is required}"
                    | otherwise = "${" <> var <> ":-}"
             in if asString
                    then literalTemplate "\"" `appendTemplate` dynamicTemplate ("$(__nix_compile_escape_json \"" <> guardedVar <> "\")") `appendTemplate` literalTemplate "\""
                    else dynamicTemplate guardedVar
        _ ->
            literalTemplate "\"\""

renderTemplateParts :: [ConfigPart] -> Template
renderTemplateParts = concatTemplates . map renderPart
  where
    renderPart (ConfigText txt) = literalTemplate (jsonEscape txt)
    renderPart (ConfigVar var) = dynamicTemplate ("$(__nix_compile_escape_json \"${" <> var <> ":?" <> var <> " is required}\")")
    renderPart (ConfigVarDefault var def) = dynamicTemplate ("$(__nix_compile_escape_json \"${" <> var <> ":-" <> def <> "}\")")
    renderPart (ConfigVarRequired var) = dynamicTemplate ("$(__nix_compile_escape_json \"${" <> var <> ":?" <> var <> " is required}\")")
    renderPart (ConfigVarAlternate var alt) = dynamicTemplate ("$(__nix_compile_escape_json \"${" <> var <> ":+" <> alt <> "}\")")
