{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--                                                                                 // emit // config
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--
--   "Machine dreams hold a special vertigo. Turner lay down on a virgin
--    slab of green temperfoam in the makeshift dorm and jacked
--    Mitchell's dossier."
--
--                                                                                      — Count Zero
--
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--                                                                             // emit // generation
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

module NixCompile.Emit.Config (
  -- * Generation
  emitConfigFunction,
  emitConfigJSON,
  emitConfigYAML,
  emitConfigTOML,

  -- * Schema helpers
  ConfigTree (..),
  buildConfigTree,
)
where

import Data.List (sortOn)
import Data.Map.Strict (Map)
import Data.Map.Strict qualified as Map
import Data.Text (Text)
import Data.Text qualified as T
import Numeric (showHex)

import NixCompile.Bash.Patterns (escapeForParamExpansion)
import NixCompile.Bash.Types

jsonEscape :: Text -> Text
jsonEscape = T.concatMap escapeChar
 where
  escapeChar '"' = "\\\""
  escapeChar '\\' = "\\\\"
  escapeChar '\n' = "\\n"
  escapeChar '\r' = "\\r"
  escapeChar '\t' = "\\t"
  escapeChar '\b' = "\\b"
  escapeChar '\f' = "\\f"
  escapeChar character
    | character < '\x20' = "\\u" <> T.justifyRight 4 '0' (T.pack (showHex (fromEnum character) ""))
    | otherwise = T.singleton character

renderJSONLit :: Literal -> Text
renderJSONLit (LitInt n) = T.pack (show n)
renderJSONLit (LitBool True) = "true"
renderJSONLit (LitBool False) = "false"
renderJSONLit (LitString s) = "\"" <> jsonEscape s <> "\""
renderJSONLit (LitPath sp) = "\"" <> jsonEscape (unStorePath sp) <> "\""

renderYAMLLit :: Literal -> Text
renderYAMLLit (LitInt n) = T.pack (show n)
renderYAMLLit (LitBool True) = "true"
renderYAMLLit (LitBool False) = "false"
renderYAMLLit (LitString s) = "\"" <> jsonEscape s <> "\""
renderYAMLLit (LitPath sp) = "\"" <> jsonEscape (unStorePath sp) <> "\""

renderTOMLLit :: Literal -> Text
renderTOMLLit (LitInt n) = T.pack (show n)
renderTOMLLit (LitBool True) = "true"
renderTOMLLit (LitBool False) = "false"
renderTOMLLit (LitString s) = "\"" <> jsonEscape s <> "\""
renderTOMLLit (LitPath sp) = "\"" <> jsonEscape (unStorePath sp) <> "\""

-- | does this config type render as a quoted string in JSON/YAML/TOML output?
cfgTypeIsStringy :: Type -> Bool
cfgTypeIsStringy TString = True
cfgTypeIsStringy TPath = True
cfgTypeIsStringy (TVar _) = True
cfgTypeIsStringy _ = False

{- | A nested config namespace: an interior 'ConfigBranch' keyed by path segment,
or a 'ConfigLeaf' holding the spec for a single dotted config path.
-}
data ConfigTree
  = ConfigBranch !(Map Text ConfigTree)
  | ConfigLeaf !ConfigSpec
  deriving (Eq, Show)

{- | Fold a flat map of dotted config paths into the nested 'ConfigTree' used by
the per-format renderers.
-}
buildConfigTree :: Map ConfigPath ConfigSpec -> ConfigTree
buildConfigTree specs = foldr insertPath (ConfigBranch Map.empty) (Map.toList specs)
 where
  insertPath ([], spec) _ = ConfigLeaf spec
  insertPath (key : keys, spec) (ConfigBranch m) =
    ConfigBranch $ Map.alter (Just . go keys spec) key m
  insertPath _ leaf = leaf
  go [] spec Nothing = ConfigLeaf spec
  go [] spec (Just _) = ConfigLeaf spec
  go (key : keys) spec Nothing =
    ConfigBranch $ Map.singleton key (go keys spec Nothing)
  go (key : keys) spec (Just (ConfigBranch m)) =
    ConfigBranch $ Map.alter (Just . go keys spec) key m
  go _ _spec (Just leaf) = leaf

-- ── emit-config bash function ─────────────────────────────────────

{- | Emit the full @emit-config@ bash function for a schema: header, the JSON
escape and int/bool require helpers, and the runtime guards + format dispatch.
-}
emitConfigFunction :: Schema -> Text
emitConfigFunction schema =
  T.unlines $
    concat
      [ emitConfigHeader
      , emitEscapeJSONFn
      , emitRequireIntFn
      , emitRequireBoolFn
      , emitRuntimeBlock schema
      ]

emitConfigHeader :: [Text]
emitConfigHeader =
  [ "# Generated by nix-compile - do not edit"
  , "emit-config() {"
  ]

emitEscapeJSONFn :: [Text]
-- shell-native JSON string escaper; mirrors the Haskell jsonEscape logic
emitEscapeJSONFn =
  [ "  __nix_compile_escape_json() {"
  , "    local s=\"$1\" out=\"\" c code esc i"
  , "    for ((i = 0; i < ${#s}; i++)); do"
  , "      c=\"${s:i:1}\""
  , "      case \"$c\" in"
  , "        '\"') out+='\\\"' ;;"
  , "        '\\') out+='\\\\' ;;"
  , "        $'\\n') out+='\\n' ;;"
  , "        $'\\r') out+='\\r' ;;"
  , "        $'\\t') out+='\\t' ;;"
  , "        $'\\b') out+='\\b' ;;"
  , "        $'\\f') out+='\\f' ;;"
  , "        *)"
  , "          printf -v code '%d' \"'$c\""
  , "          if (( code < 32 )); then"
  , "            printf -v esc '\\\\u%04x' \"$code\""
  , "            out+=\"$esc\""
  , "          else"
  , "            out+=\"$c\""
  , "          fi"
  , "          ;;"
  , "      esac"
  , "    done"
  , "    printf '%s' \"$out\""
  , "  }"
  ]

emitRequireIntFn :: [Text]
-- n.b. checks both value-shape and JSON lexical rules (no leading zeros)
emitRequireIntFn =
  [ "  __nix_compile_require_int() {"
  , "    case \"$2\" in"
  , "      -[0-9]*|[0-9]*) ;;"
  , "      *) echo \"$1 must be an integer\" >&2; return 1 ;;"
  , "    esac"
  , "    case \"$2\" in"
  , "      *[!0-9-]*|*-*-*|*-) "
  , "        echo \"$1 must be an integer\" >&2; return 1 ;;"
  , "    esac"
  , "    case \"$2\" in"
  , "      0|-0|[1-9]*|-[1-9]*) ;;"
  , "      *) echo \"$1 must be a JSON integer (no leading zeros)\" >&2; return 1 ;;"
  , "    esac"
  , "    case \"$2\" in"
  , "      *) printf '%s' \"$2\" ;;"
  , "    esac"
  , "  }"
  ]

emitRequireBoolFn :: [Text]
emitRequireBoolFn =
  [ "  __nix_compile_require_bool() {"
  , "    case \"$2\" in"
  , "      true|false) printf '%s' \"$2\" ;;"
  , "      *) echo \"$1 must be true or false\" >&2; return 1 ;;"
  , "    esac"
  , "  }"
  ]

emitRuntimeBlock :: Schema -> [Text]
-- format dispatch + runtime guards; renderRuntimeGuards is multi-line
emitRuntimeBlock schema =
  [ "  local format=\"${1:-json}\""
  , renderRuntimeGuards schema
  , "  case \"$format\" in"
  , "    json)"
  , "      " <> emitConfigJSON schema
  , "      ;;"
  , "    yaml)"
  , "      " <> emitConfigYAML schema
  , "      ;;"
  , "    toml)"
  , "      " <> emitConfigTOML schema
  , "      ;;"
  , "    *)"
  , "      echo \"Unknown format: $format\" >&2"
  , "      return 1"
  , "      ;;"
  , "  esac"
  , "}"
  ]

isRequiredEnv :: Map Text EnvSpec -> Text -> Bool
isRequiredEnv env var = maybe True envRequired (Map.lookup var env)

renderRuntimeGuards :: Schema -> Text
renderRuntimeGuards schema =
  T.unlines
    [ guardLine
    | spec <- Map.elems (schemaConfig schema)
    , guardLine <- renderGuards spec
    ]
 where
  env = schemaEnv schema

  renderGuards ConfigSpec{cfgFrom = Just var, cfgType = ty, cfgQuoted = quoted}
    | isRequiredEnv env var = requiredGuard env var ty quoted
    | otherwise = []
  renderGuards ConfigSpec{cfgTemplate = Just parts} =
    [presenceGuard var | var <- requiredTemplateVars parts, isRequiredEnv env var]
  renderGuards _ = []

  presenceGuard var = "  : \"${" <> var <> ":?" <> var <> " is required}\""
  intGuard var =
    "  __nix_compile_require_int \""
      <> var
      <> "\" \"${"
      <> var
      <> ":?"
      <> var
      <> " is required}\" >/dev/null || return 1"
  boolGuard var =
    "  __nix_compile_require_bool \""
      <> var
      <> "\" \"${"
      <> var
      <> ":?"
      <> var
      <> " is required}\" >/dev/null || return 1"

  requiredGuard _ var _ (Just Quoted) = [presenceGuard var]
  requiredGuard _ var ty _quoted
    | TInt <- ty = [intGuard var]
    | TNumeric <- ty = [intGuard var]
    | TBool <- ty = [boolGuard var]
    | otherwise = [presenceGuard var]

  requiredTemplateVars = concatMap templateVar
   where
    templateVar (ConfigVar var) = [var]
    templateVar (ConfigVarRequired var) = [var]
    templateVar _ = []

-- | Emit the bash @printf@ statement that prints the schema's config as JSON.
emitConfigJSON :: Schema -> Text
emitConfigJSON schema =
  let env = schemaEnv schema
      tree = buildConfigTree (schemaConfig schema)
   in emitTemplate (renderJSONTree env 0 tree)

escapeForPrintf :: Text -> Text
escapeForPrintf = T.concatMap escapeChar
 where
  escapeChar '\'' = "'\\''"
  escapeChar character = T.singleton character

data Template = Template !Text ![Text]

appendTemplate :: Template -> Template -> Template
appendTemplate (Template a as) (Template b bs) = Template (a <> b) (as ++ bs)

concatTemplates :: [Template] -> Template
concatTemplates = foldr appendTemplate (Template "" [])

literalTemplate :: Text -> Template
literalTemplate text = Template (T.replace "%" "%%" text) []

dynamicTemplate :: Text -> Template
dynamicTemplate arg = Template "%s" [arg]

emitTemplate :: Template -> Text
emitTemplate (Template fmt args) =
  "printf '" <> escapeForPrintf (fmt <> "\n") <> "'" <> argsText
 where
  argsText
    | null args = ""
    | otherwise = " " <> T.unwords (map quoteShellArg args)

  quoteShellArg arg = "\"" <> arg <> "\""

intersperseTemplate :: Template -> [Template] -> [Template]
intersperseTemplate _ [] = []
intersperseTemplate _ [x] = [x]
intersperseTemplate sep (x : xs) = x : sep : intersperseTemplate sep xs

renderJSONTree :: Map Text EnvSpec -> Int -> ConfigTree -> Template
renderJSONTree env indent = go
 where
  go (ConfigBranch m) | Map.null m = literalTemplate "{}"
  go (ConfigBranch m) =
    let entries = Map.toList m
        rendered = map (renderEntry indent) entries
        indentStr = T.replicate indent "  "
        nextIndent = T.replicate (indent + 1) "  "
     in concatTemplates $
          [literalTemplate "{\n"]
            ++ intersperseTemplate
              (literalTemplate ",\n")
              (map (appendTemplate (literalTemplate nextIndent)) rendered)
            ++ [literalTemplate ("\n" <> indentStr <> "}")]
  go (ConfigLeaf spec) = renderJSONValue env spec

  renderEntry ind (key, subtree) =
    literalTemplate ("\"" <> key <> "\": ") `appendTemplate` renderJSONTree env (ind + 1) subtree

renderJSONValue :: Map Text EnvSpec -> ConfigSpec -> Template
renderJSONValue env ConfigSpec{..} = go cfgFrom cfgLit cfgTemplate
 where
  go _ (Just lit) _ = literalTemplate (renderJSONLit lit)
  go _ _ (Just parts) =
    literalTemplate "\""
      `appendTemplate` renderTemplateParts parts
      `appendTemplate` literalTemplate "\""
  go (Just var) _ _ =
    let required = isRequiredEnv env var
        forceString = cfgQuoted == Just Quoted
        asString = forceString || cfgTypeIsStringy cfgType
        guardedVar
          | required = "${" <> var <> ":?" <> var <> " is required}"
          | otherwise = "${" <> var <> ":-}"
     in if asString
          then
            literalTemplate "\""
              `appendTemplate` dynamicTemplate
                ("$(__nix_compile_escape_json \"" <> guardedVar <> "\")")
              `appendTemplate` literalTemplate "\""
          else dynamicTemplate guardedVar
  go _ _ _ = literalTemplate "null"

-- | Emit the bash @printf@ statement that prints the schema's config as YAML.
emitConfigYAML :: Schema -> Text
emitConfigYAML schema =
  let env = schemaEnv schema
      tree = buildConfigTree (schemaConfig schema)
   in emitTemplate (renderYAMLTree env 0 tree)

renderYAMLTree :: Map Text EnvSpec -> Int -> ConfigTree -> Template
renderYAMLTree env indent = go
 where
  go (ConfigBranch m) | Map.null m = literalTemplate "{}"
  go (ConfigBranch m) =
    let entries = sortOn fst (Map.toList m)
        rendered = map (renderYAMLEntry indent) entries
     in concatTemplates (intersperseTemplate (literalTemplate "\n") rendered)
  go (ConfigLeaf spec) = renderYAMLValue env spec

  renderYAMLEntry ind (key, subtree) = render subtree
   where
    indentStr = T.replicate ind "  "
    render (ConfigBranch _) =
      literalTemplate (indentStr <> key <> ":\n")
        `appendTemplate` renderYAMLTree env (ind + 1) subtree
    render (ConfigLeaf spec') =
      literalTemplate (indentStr <> key <> ": ") `appendTemplate` renderYAMLValue env spec'

renderYAMLValue :: Map Text EnvSpec -> ConfigSpec -> Template
renderYAMLValue env ConfigSpec{..} = go cfgFrom cfgLit cfgTemplate
 where
  go _ (Just lit) _ = literalTemplate (renderYAMLLit lit)
  go _ _ (Just parts) =
    literalTemplate "\""
      `appendTemplate` renderTemplateParts parts
      `appendTemplate` literalTemplate "\""
  go (Just var) _ _ =
    let required = isRequiredEnv env var
        forceString = cfgQuoted == Just Quoted
        asString = forceString || cfgTypeIsStringy cfgType
        guardedVar
          | required = "${" <> var <> ":?" <> var <> " is required}"
          | otherwise = "${" <> var <> ":-}"
     in if asString
          then
            literalTemplate "\""
              `appendTemplate` dynamicTemplate
                ("$(__nix_compile_escape_json \"" <> guardedVar <> "\")")
              `appendTemplate` literalTemplate "\""
          else dynamicTemplate guardedVar
  go _ _ _ = literalTemplate "null"

-- | Emit the bash @printf@ statement that prints the schema's config as TOML.
emitConfigTOML :: Schema -> Text
emitConfigTOML schema =
  let env = schemaEnv schema
      tree = buildConfigTree (schemaConfig schema)
   in emitTemplate (renderTOMLTree env [] tree)

renderTOMLTree :: Map Text EnvSpec -> [Text] -> ConfigTree -> Template
renderTOMLTree env path = go
 where
  go (ConfigBranch m) | Map.null m = literalTemplate ""
  go (ConfigBranch m) =
    let (leaves, branches) = Map.partitionWithKey isLeaf m
        isLeaf _ (ConfigLeaf _) = True
        isLeaf _ _ = False
        sectionHeader =
          if not (null path) && not (Map.null leaves)
            then "[" <> T.intercalate "." path <> "]\n"
            else ""
        leafLines = map renderTOMLLeaf (sortOn fst (Map.toList leaves))
        branchLines = map (renderTOMLBranch path) (sortOn fst (Map.toList branches))
     in concatTemplates $
          [literalTemplate sectionHeader]
            ++ intersperseTemplate (literalTemplate "\n") leafLines
            ++ [ literalTemplate
                   (if not (Map.null leaves) && not (Map.null branches) then "\n\n" else "")
               ]
            ++ intersperseTemplate (literalTemplate "\n\n") branchLines
  go (ConfigLeaf _) = literalTemplate ""
  renderTOMLLeaf (key, ConfigLeaf spec) =
    literalTemplate (key <> " = ") `appendTemplate` renderTOMLValue env spec
  renderTOMLLeaf _ = literalTemplate ""

  renderTOMLBranch parentPath (key, subtree) =
    renderTOMLTree env (parentPath ++ [key]) subtree

renderTOMLValue :: Map Text EnvSpec -> ConfigSpec -> Template
renderTOMLValue env ConfigSpec{..} = go cfgFrom cfgLit cfgTemplate
 where
  go _ (Just lit) _ = literalTemplate (renderTOMLLit lit)
  go _ _ (Just parts) =
    literalTemplate "\""
      `appendTemplate` renderTemplateParts parts
      `appendTemplate` literalTemplate "\""
  go (Just var) _ _ =
    let required = isRequiredEnv env var
        forceString = cfgQuoted == Just Quoted
        asString = forceString || cfgTypeIsStringy cfgType
        guardedVar
          | required = "${" <> var <> ":?" <> var <> " is required}"
          | otherwise = "${" <> var <> ":-}"
     in if asString
          then
            literalTemplate "\""
              `appendTemplate` dynamicTemplate
                ("$(__nix_compile_escape_json \"" <> guardedVar <> "\")")
              `appendTemplate` literalTemplate "\""
          else dynamicTemplate guardedVar
  go _ _ _ = literalTemplate "\"\""

renderTemplateParts :: [ConfigPart] -> Template
renderTemplateParts = concatTemplates . map renderPart
 where
  renderPart (ConfigText txt) = literalTemplate (jsonEscape txt)
  renderPart (ConfigVar var) =
    dynamicTemplate
      ("$(__nix_compile_escape_json \"${" <> var <> ":?" <> var <> " is required}\")")
  -- n.b. escape def/alt before embedding (closes C1 from review-2). The user-controlled
  -- default text from `${VAR:-…}` flows in raw; bash would otherwise evaluate $(…), backticks,
  -- etc. inside the default and execute arbitrary commands.
  renderPart (ConfigVarDefault var def) =
    dynamicTemplate
      ("$(__nix_compile_escape_json \"${" <> var <> ":-" <> escapeForParamExpansion def <> "}\")")
  renderPart (ConfigVarRequired var) =
    dynamicTemplate
      ("$(__nix_compile_escape_json \"${" <> var <> ":?" <> var <> " is required}\")")
  renderPart (ConfigVarAlternate var alt) =
    dynamicTemplate
      ("$(__nix_compile_escape_json \"${" <> var <> ":+" <> escapeForParamExpansion alt <> "}\")")
