{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}

-- |
-- Module      : NixCompile.Emit.Config
-- Description : Generate emit-config bash function
--
-- The key innovation of nix-compile: generating bash functions that output
-- structured config (JSON/YAML/TOML) based on config.* assignments.
--
-- Instead of heredoc templating:
-- @
-- cat << EOF > config.json
-- {
--   "server": {
--     "port": ${PORT},
--     "host": "${HOST}"
--   }
-- }
-- EOF
-- @
--
-- You write:
-- @
-- config.server.port=$PORT
-- config.server.host="$HOST"
-- emit-config json > config.json
-- @
--
-- The emit-config function is generated at build time with the correct
-- structure based on static analysis. Type safety is enforced: unquoted
-- values become JSON numbers/booleans, quoted become strings.
module NixCompile.Emit.Config
  ( -- * Generation
    emitConfigFunction,
    emitConfigJson,
    emitConfigYaml,
    emitConfigToml,

    -- * Schema helpers
    ConfigTree (..),
    buildConfigTree,
  )
where

import Data.List (sortOn)
import Data.Map.Strict (Map)
import Data.Map.Strict qualified as Map
import Data.Text (Text)
import Data.Text qualified as T
import NixCompile.Types

-- | Minimal JSON-style escaping for double-quoted strings.
-- Used for emitting literal config values safely.
jsonEscape :: Text -> Text
jsonEscape = T.concatMap $ \c -> case c of
  '"' -> "\\\""
  '\\' -> "\\\\"
  '\n' -> "\\n"
  '\r' -> "\\r"
  '\t' -> "\\t"
  _ -> T.singleton c

-- | Render a literal as JSON
renderJsonLit :: Literal -> Text
renderJsonLit = \case
  LitInt n -> T.pack (show n)
  LitBool True -> "true"
  LitBool False -> "false"
  LitString s -> "\"" <> jsonEscape s <> "\""
  LitPath sp -> "\"" <> jsonEscape (unStorePath sp) <> "\""

-- | Render a literal as YAML
renderYamlLit :: Literal -> Text
renderYamlLit = \case
  LitInt n -> T.pack (show n)
  LitBool True -> "true"
  LitBool False -> "false"
  LitString s -> "\"" <> jsonEscape s <> "\""
  LitPath sp -> "\"" <> jsonEscape (unStorePath sp) <> "\""

-- | Render a literal as TOML
renderTomlLit :: Literal -> Text
renderTomlLit = \case
  LitInt n -> T.pack (show n)
  LitBool True -> "true"
  LitBool False -> "false"
  LitString s -> "\"" <> jsonEscape s <> "\""
  LitPath sp -> "\"" <> jsonEscape (unStorePath sp) <> "\""

-- | A tree representation of config structure
-- config.server.port -> ConfigLeaf "server" (ConfigLeaf "port" (ConfigValue ...))
data ConfigTree
  = ConfigBranch !(Map Text ConfigTree)
  | ConfigLeaf !ConfigSpec
  deriving (Eq, Show)

-- | Build a config tree from flat config specs
-- [["server", "port"]] -> { server: { port: ... } }
buildConfigTree :: Map ConfigPath ConfigSpec -> ConfigTree
buildConfigTree specs = foldr insertPath (ConfigBranch Map.empty) (Map.toList specs)
  where
    insertPath ([], spec) _ = ConfigLeaf spec
    insertPath (k : ks, spec) (ConfigBranch m) =
      ConfigBranch $ Map.alter (Just . go ks spec) k m
    insertPath _ leaf = leaf -- shouldn't happen
    go [] spec Nothing = ConfigLeaf spec
    go [] spec (Just _) = ConfigLeaf spec -- overwrite
    go (k : ks) spec Nothing =
      ConfigBranch $ Map.singleton k (go ks spec Nothing)
    go (k : ks) spec (Just (ConfigBranch m)) =
      ConfigBranch $ Map.alter (Just . go ks spec) k m
    go _ _spec (Just leaf) = leaf -- can't descend into leaf

-- | Generate the emit-config bash function
-- This function will be injected into the script at build time
-- NOTE: Does NOT use heredocs (that would violate our own policy)
emitConfigFunction :: Schema -> Text
emitConfigFunction schema =
  T.unlines
    [ "# Generated by nix-compile - do not edit",
      "emit-config() {",
      "  __nix_compile_escape_json() {",
      "    local s=\"$1\"",
      "    s=${s//\\\\/\\\\\\\\}",
      "    s=${s//\\\"/\\\\\\\"}",
      "    s=${s//$'\\n'/\\\\n}",
      "    s=${s//$'\\r'/\\\\r}",
      "    s=${s//$'\\t'/\\\\t}",
      "    printf '%s' \"$s\"",
      "  }",
      "  local format=\"${1:-json}\"",
      "  case \"$format\" in",
      "    json)",
      "      " <> emitConfigJson schema,
      "      ;;",
      "    yaml)",
      "      " <> emitConfigYaml schema,
      "      ;;",
      "    toml)",
      "      " <> emitConfigToml schema,
      "      ;;",
      "    *)",
      "      echo \"Unknown format: $format\" >&2",
      "      return 1",
      "      ;;",
      "  esac",
      "}"
    ]

-- | Generate JSON output command using printf (no heredocs)
emitConfigJson :: Schema -> Text
emitConfigJson schema =
  let tree = buildConfigTree (schemaConfig schema)
   in "printf '%s\\n' '" <> escapeForPrintf (renderJsonTree 0 tree) <> "'"

-- | Escape a string for use in single-quoted printf argument
escapeForPrintf :: Text -> Text
escapeForPrintf = T.concatMap $ \case
  '\'' -> "'\\''" -- End quote, escaped quote, start quote
  c -> T.singleton c

-- | NixCompile config tree as JSON
renderJsonTree :: Int -> ConfigTree -> Text
renderJsonTree indent = \case
  ConfigBranch m | Map.null m -> "{}"
  ConfigBranch m ->
    let entries = Map.toList m
        rendered = map (renderEntry indent) entries
        indentStr = T.replicate indent "  "
        nextIndent = T.replicate (indent + 1) "  "
     in "{\n"
          <> T.intercalate ",\n" (map (nextIndent <>) rendered)
          <> "\n"
          <> indentStr
          <> "}"
  ConfigLeaf spec -> renderJsonValue spec
  where
    renderEntry ind (key, subtree) =
      "\"" <> key <> "\": " <> renderJsonTree (ind + 1) subtree

-- | NixCompile a config value as JSON
-- Uses bash variable expansion, with quoting based on type.
-- All variable references use ${VAR:?} to fail fast if unset,
-- preventing malformed output at runtime.
renderJsonValue :: ConfigSpec -> Text
renderJsonValue ConfigSpec {..} =
  case (cfgFrom, cfgLit) of
    (_, Just lit) ->
      renderJsonLit lit
    (Just var, _) ->
      let forceString = cfgQuoted == Just Quoted
          asString =
            forceString || case cfgType of
              TString -> True
              TPath -> True
              TVar _ -> True
              _ -> False
          guardedVar = "${" <> var <> ":?" <> var <> " is required}"
       in if asString
            then "\"$(__nix_compile_escape_json \"" <> guardedVar <> "\")\""
            else guardedVar
    _ ->
      "null"

-- | Generate YAML output command using printf (no heredocs)
emitConfigYaml :: Schema -> Text
emitConfigYaml schema =
  let tree = buildConfigTree (schemaConfig schema)
   in "printf '%s\\n' '" <> escapeForPrintf (renderYamlTree 0 tree) <> "'"

-- | NixCompile config tree as YAML
renderYamlTree :: Int -> ConfigTree -> Text
renderYamlTree indent = \case
  ConfigBranch m | Map.null m -> "{}"
  ConfigBranch m ->
    let entries = sortOn fst (Map.toList m)
        rendered = map (renderYamlEntry indent) entries
     in T.intercalate "\n" rendered
  ConfigLeaf spec -> renderYamlValue spec
  where
    renderYamlEntry ind (key, subtree) =
      let indentStr = T.replicate ind "  "
       in case subtree of
            ConfigBranch _ ->
              indentStr <> key <> ":\n" <> renderYamlTree (ind + 1) subtree
            ConfigLeaf spec ->
              indentStr <> key <> ": " <> renderYamlValue spec

-- | NixCompile a config value as YAML
renderYamlValue :: ConfigSpec -> Text
renderYamlValue ConfigSpec {..} =
  case (cfgFrom, cfgLit) of
    (_, Just lit) ->
      renderYamlLit lit
    (Just var, _) ->
      let forceString = cfgQuoted == Just Quoted
          asString =
            forceString || case cfgType of
              TString -> True
              TPath -> True
              TVar _ -> True
              _ -> False
          guardedVar = "${" <> var <> ":?" <> var <> " is required}"
       in if asString
            then "\"$(__nix_compile_escape_json \"" <> guardedVar <> "\")\""
            else guardedVar
    _ ->
      "null"

-- | Generate TOML output command using printf (no heredocs)
emitConfigToml :: Schema -> Text
emitConfigToml schema =
  let tree = buildConfigTree (schemaConfig schema)
   in "printf '%s\\n' '" <> escapeForPrintf (renderTomlTree [] tree) <> "'"

-- | NixCompile config tree as TOML
renderTomlTree :: [Text] -> ConfigTree -> Text
renderTomlTree path = \case
  ConfigBranch m | Map.null m -> ""
  ConfigBranch m ->
    let -- Separate leaves (direct values) from branches (sections)
        (leaves, branches) = Map.partitionWithKey isLeaf m
        isLeaf _ (ConfigLeaf _) = True
        isLeaf _ _ = False
        -- NixCompile section header if we have leaves and a path
        sectionHeader =
          if not (null path) && not (Map.null leaves)
            then "[" <> T.intercalate "." path <> "]\n"
            else ""
        -- NixCompile leaf values
        leafLines =
          map renderTomlLeaf (sortOn fst (Map.toList leaves))
        -- NixCompile subsections
        branchLines =
          map (renderTomlBranch path) (sortOn fst (Map.toList branches))
     in sectionHeader
          <> T.intercalate "\n" leafLines
          <> (if not (Map.null leaves) && not (Map.null branches) then "\n\n" else "")
          <> T.intercalate "\n\n" branchLines
  ConfigLeaf _ -> "" -- shouldn't be called at top level
  where
    renderTomlLeaf (key, ConfigLeaf spec) =
      key <> " = " <> renderTomlValue spec
    renderTomlLeaf _ = ""

    renderTomlBranch parentPath (key, subtree) =
      renderTomlTree (parentPath ++ [key]) subtree

-- | NixCompile a config value as TOML
renderTomlValue :: ConfigSpec -> Text
renderTomlValue ConfigSpec {..} =
  case (cfgFrom, cfgLit) of
    (_, Just lit) ->
      renderTomlLit lit
    (Just var, _) ->
      let forceString = cfgQuoted == Just Quoted
          asString =
            forceString || case cfgType of
              TString -> True
              TPath -> True
              TVar _ -> True
              _ -> False
          guardedVar = "${" <> var <> ":?" <> var <> " is required}"
       in if asString
            then "\"$(__nix_compile_escape_json \"" <> guardedVar <> "\")\""
            else guardedVar
    _ ->
      "\"\"" -- TOML has no null; emit empty string as safe default
